### ISSUE TITLE
Blanked out Custom Controls after installing

### ISSUE THREAD

**Issue by LewisSpring** [jneilliii/OctoPrint-BLTouch#16]
Hi there, i installed this plugin and it wiped all my custom controls.

I managed to recover them with a backup.

Is this intended behaviour?

Thanks

**Comment by jneilliii** [comment]
That is actually an issue with the custom control editor plugin, assuming you have that installed. There's a ticket in that plugin's repo about it. My recommendation if you do have that plugin installed is to disable it after setting up your custom controls, otherwise you risk the same thing happening again.

**Comment by LewisSpring** [comment]
Hi @jneilliii, thanks for your reply.

I do have that installed. Interesting issue! 

Since i'm constantly editing my controls at the moment, I'll make some controls and copy the yaml. I'll post it here in a few for anyone else who wants them.

Thanks!

**Comment by LewisSpring** [comment]
[see txt file, the line breaks get butchered]
[bltouch customcontrols.txt](https://github.com/jneilliii/OctoPrint-BLTouch/files/4853055/bltouch.customcontrols.txt)
