### ISSUE TITLE
Config commands don't take effect right away

### ISSUE THREAD

**Issue by phord** [jneilliii/OctoPrint-BLTouch#7]
When I configure this plugin, the changes are not effective until I restart OctoPrint. This takes a few minutes on my installation, so it's a bit painful to config this plugin.

**Comment by jneilliii** [comment]
I'll investigate how I'm doing the binding and sending the commands.  This plugin was one of my earlier ones and I've since learned a little more about how the knockout binding works.

**Comment by jneilliii** [comment]
I had to take a slightly different approach for this one.  Because of the way the buttons are getting injected by OctoPrint itself using a callback function there is no way to work around the binding.  I was however able to get it to inject a javascript command that can read those settings on the fly, resulting in a no-reload situation when changing the commands.  Give it a try by installing the updated code using the below url in plugin manager.  Once installed it will have to reload (sorry can't help that) to reload the updated code. Once I hear back from you I'll release an official release with this improvement.

https://github.com/jneilliii/OctoPrint-BLTouch/archive/0.3.0.zip
